CHANGELOG.md
lib/prawn/document/internals.rb
spec/document_spec.rb

A simple patch that delegates `on_page_create` calls to `renderer.on_page_create`.

Delegate on_page_create method to renderer. #797

---

CHANGELOG.md

Fix up commit cde833ef (Add missing CHANGELOG.md file).

CHANGELOG.md: Fix typo in `:shrink_to_fit`

---

manual/text/positioned_text.rb

Fix up commit c709a25f (Added positioned text examples.) by replacing
*Given that said, …* by *Given that, …*.
*That said, …* would have been fine too.

manual/text/positioned_text.rb: Improve wording

---

spec/images_spec.rb

These tests test image scaling when either `height` or `width` is used
as an option.

Add additional scale image tests

---

CHANGELOG.md
lib/prawn/stamp.rb
spec/stamp_spec.rb

This is a fix for a known bug that has been present within Prawn for some time now. Previously, links were not clickable in stamps because annotations were only referred from the stamp's XObject. This patch adds the necessary annotation references to the page object that the stamp was called from.
This patch should also be a fix for links within repeaters, as mentioned in #498.
_(Sorry, it looks like my text editor removed trailing spaces from the changelog - hopefully this doesn't clutter up the commit)_

Fix links/annotations within stamps. #801

---

.rubocop.yml
lib/prawn/document.rb

This PR enables the CommentIndentation cop to ensure that code comments appear at the same indentation of the code they are commenting.

Enforce correct comment indentation.

---

.rubocop.yml
spec/document_spec.rb
spec/graphics_spec.rb
spec/outline_spec.rb
spec/text_box_spec.rb

This PR enforces removing unnecessary method call parentheses.

Remove unnecessary method call parentheses

---

.rubocop.yml
lib/prawn/font/afm.rb
lib/prawn/grid.rb
lib/prawn/security.rb
lib/prawn/text/formatted/box.rb
spec/text_spec.rb

This PR enforces a preference for symbol to proc and enables the correct rubocop cop for that.

Enforce preference for symbol to proc

---

.rubocop.yml
lib/prawn/document.rb
lib/prawn/measurements.rb
spec/font_spec.rb
spec/graphics_spec.rb
spec/grid_spec.rb
spec/spec_helper.rb

This PR does a few things related to cleaning up comments.
- Removes some Unneeded comments
- Ensures there is a leading space after the comment
- Ensures a space precedes a comment
- Enforces preference not to use block comments

Comment cleanup

---

.rubocop.yml
lib/prawn/font/afm.rb

When appropriate we want to use each_with_object instead of inject with the extra return statement.

Enforce preference for each_with_object.

---

.rubocop.yml
lib/prawn/font.rb
lib/prawn/graphics/patterns.rb
lib/prawn/soft_mask.rb
spec/document_spec.rb
spec/span_spec.rb

This PR removes redundant braces around hash parameters. This sets is up for some easier use of other alignment style guidelines and makes usage of named parameters more consistent if and when we use those. It

Remove redundant braces.

---

.rubocop.yml
bench/table_bench.rb
lib/prawn/document.rb
lib/prawn/font/afm.rb
lib/prawn/grid.rb
lib/prawn/images.rb
manual/cover.rb
manual/text/registering_families.rb
spec/document_spec.rb
spec/formatted_text_arranger_spec.rb
spec/formatted_text_box_spec.rb
spec/formatted_text_fragment_spec.rb
spec/graphics_spec.rb
spec/inline_formatted_text_parser_spec.rb
spec/line_wrap_spec.rb
spec/security_spec.rb
spec/text_at_spec.rb
spec/text_spec.rb

This PR enforces a few styles related to hashes
- It enforces correct key indentation
- Removes use of deprecated Hash#has_key? method
- Enforces correct spacing inside hash braces.

Hash cleanup

---

.rubocop.yml
spec/font_spec.rb

This PR enforces a preference for {} over Hash.new. It also enforces [] over Array.new and "" over String.new.

Prefer {} over Hash.new

---

.rubocop.yml
lib/prawn/font/afm.rb
lib/prawn/graphics.rb
lib/prawn/graphics/patterns.rb
lib/prawn/security.rb
lib/prawn/text.rb
lib/prawn/text/formatted/parser.rb
spec/formatted_text_box_spec.rb

Various cleanups related to indentation, symbol quoting, multi-line ternary statements, unless/else rewrites, removing character literals and removing useless private modifier.

More cleanups

---

.rubocop.yml
lib/prawn.rb
lib/prawn/document.rb
lib/prawn/font/afm.rb
lib/prawn/font/ttf.rb
lib/prawn/graphics.rb
lib/prawn/images/png.rb
lib/prawn/text.rb
lib/prawn/text/formatted/line_wrap.rb
lib/prawn/text/formatted/parser.rb
spec/bounding_box_spec.rb
spec/formatted_text_arranger_spec.rb
spec/formatted_text_box_spec.rb
spec/formatted_text_fragment_spec.rb
spec/graphics_spec.rb
spec/inline_formatted_text_parser_spec.rb
spec/line_wrap_spec.rb
spec/png_spec.rb
spec/stamp_spec.rb
spec/text_at_spec.rb
spec/text_box_spec.rb
spec/text_rendering_mode_spec.rb
spec/text_spacing_spec.rb
spec/text_spec.rb
spec/text_with_inline_formatting_spec.rb
spec/transparency_spec.rb

This PR enforces consistent multi-line string concatenation prefering to use `\` instead of the previously used `>>` and `+`.

Enforce consistent multi-line string concatenation

---

.rubocop.yml
spec/font_spec.rb
spec/outline_spec.rb

Prefer the rspec idiomatic `be_nil` instead of comparing with `== nil`

Prefer be_nil instead of == nil.

---

.rubocop.yml
lib/prawn/document.rb
lib/prawn/document/bounding_box.rb
lib/prawn/font.rb
lib/prawn/font_metric_cache.rb
lib/prawn/graphics.rb
lib/prawn/text.rb
lib/prawn/text/formatted/line_wrap.rb
spec/bounding_box_spec.rb
spec/document_spec.rb
spec/font_metric_cache_spec.rb
spec/font_spec.rb
spec/graphics_spec.rb
spec/grid_spec.rb
spec/repeater_spec.rb

This PR
- makes a few cops disabled with explanations
- enforces no spaces inside parenthesis
- enforces a preference for calling #even? and #odd? over modulo 2 operations
- enforces a single space before the first method argument
- enforces a preference for attr_reader for trivial accessors.

Minor cleanups

---

.rubocop.yml
lib/prawn/document.rb

This brings consistency renaming @internal_state to @state and making it an attr_accessor that's used internally everywhere.
Everywhere was already accessing @internal_state via a state method that acted as an attr_reader for the instance variable.

Rename internal state

---

README.md

With the merging of #845 we now have new code in master that hasn't been released. I'm proposing we commit to a regular 6 week release to roll up and release any new commits to help prevent development stagnation. I proposed 6 weeks because that is the release cycle used by other major open source projects (Google Chrome, Firefox, Ember.js) and I have found it easy to keep up to date with updates to those projects when I needed to. 
If no code has been merged into master during a 6 week cycle, we wouldn't cut a release. I would expect most releases to be a minor version bump. If we have a major feature release we can discuss making a minor (or major) version bump and any backwards incompatible changes would also be a major release, in line with the current versioning policy.
An open …

Add new release policy to README.md

---

lib/prawn/font.rb

this PR is related to an issue I'm facing with a PR from prawn-templates (see https://github.com/prawnpdf/prawn-templates/pull/3)

change font id generation

---

CHANGELOG.md
lib/prawn/graphics/patterns.rb
lib/prawn/text/formatted/arranger.rb
lib/prawn/text/formatted/line_wrap.rb

I generally run IRB with all warnings enabled (I have an alias to `irb -w` setup in my shell).
After requiring the current master branch of `Prawn` in IRB on Ruby 2.2.0, the following warnings were logged:
```bash
> irb -w
2.2.0 :001 > require './lib/prawn'
/Users/jesse/development/ruby/prawn/lib/prawn/text/formatted/line_wrap.rb:153: warning: private attribute?
/Users/jesse/development/ruby/prawn/lib/prawn/text/formatted/line_wrap.rb:154: warning: private attribute?
/Users/jesse/development/ruby/prawn/lib/prawn/text/formatted/arranger.rb:222: warning: private attribute?
/Users/jesse/development/ruby/prawn/lib/prawn/graphics/patterns.rb:79: warning: assigned but unused variable - x1
/Users/jesse/development/ruby/prawn/lib/prawn/graphics/patterns.rb:79: warning: assigned but unused …
```

Fix IRB warnings on Ruby >= 2.2.0

---

.travis.yml

We have a few failing builds on master because of conflict between new rubygems and older bundler.
This PR fixes build of master branch after merge of #920.

Install latest bundler before bundling the build

---

prawn.gemspec

* Make it clear that Prawn license is a bit different to Ruby license
* Use recommented names for GPL

Fixed Rubygems licenses

---

prawn.gemspec
spec/document_spec.rb
spec/font_spec.rb
spec/graphics_spec.rb
spec/repeater_spec.rb
spec/spec_helper.rb
spec/text_at_spec.rb
spec/text_box_spec.rb
spec/text_spec.rb

This is mostly a mechanical changes.
* Replaced all `.should` with `expect()`
* Removed deprecated options
* Unrolled some blocks
* Cleaned up everything that RSpec complained about

Update to RSpec 3

---

prawn.gemspec

At the moment Yard has some problems with the latest Rake. Let's not break everybody's code because of that.
Hopefully the incompatibility (lsegal/yard#946) is going to be resolved by the time of next Prawn release and we will loosen the requirement.

Fix Yard-Rake incompatibility

---

CHANGELOG.md
lib/prawn/graphics/patterns.rb
manual/graphics/gradients.rb
spec/graphics_spec.rb

Another change towards getting SVG support going.  From the changelog:
> Previously, only two colors could be specified in a gradient: the start
> and end colors.  This change allows any number of colors to be specified,
> along with the position between 0 and 1 as to where they should be displayed.
> 
> This change also comes with a change to the format of the `fill_gradient`
> and `stroke_gradient` methods.  You can continue to use the old method
> parameters and only specify two colors, or use the new keyword arguments
> to specify arbitrary stops.
> 
> As a bonus, if you use the new method style, `apply_transformations` is
> set true automatically (see below).
Two things you might be curious about:
1. The original code calls `.dup.freeze` after calling `normalize_color`.  I can't see …

Gradients can have multiple stops to blend more than two colors

---

lib/prawn/graphics/patterns.rb
spec/graphics_spec.rb

`hash` method returns same hash value for the same object but that only works in the same process. The resulting hash is not consistent between processes. This resulted in a different pattern name each time the process would restart.
New way of pattern name derivation is consistent between runs.

Consistent Pattern naming

---

lib/prawn/document.rb
spec/document_spec.rb

Currently, usage like this:
```ruby
Prawn::Document.new.start_new_page({margin: 0}.freeze)
```
will raise:
```ruby
RuntimeError: can't modify frozen Hash
```
The mutation happens in `apply_margin_options`, and only when the `:margin` key is present. This PR refactors that method so that it doesn't need the options hash for temporary storage.
See more details here: https://github.com/prawnpdf/prawn/issues/962

Don't mutate options hash in Document#start_new_page

---

lib/prawn/graphics/dash.rb
spec/graphics_spec.rb
spec/stroke_styles_spec.rb

The PDF 1.7 specification says that the dash array can contain zeros but that not all numbers must be zero.
Additionally, a single dash length or any number in a dash array may not be negative.
This fixes #999 which is based on the discussion at https://github.com/prawnpdf/prawn/commit/e65c24411c451918718a8e8cb35631c98ccc5517#commitcomment-20067863

Fix dash implementation to conform to spec

---

manual/graphics/gradients.rb

Our gradients manual looked broken for some time. This is a fix. It's only a layout fix. No content has changed. No lib code has changed either.
Before:
After:

Fix Gradients manual layout

---

lib/prawn/font_metric_cache.rb
lib/prawn/text/formatted/arranger.rb
lib/prawn/text/formatted/line_wrap.rb
spec/line_wrap_spec.rb

This is a subtle bug with a complex solution.
While working on spec for manual (#949) I've noticed that word wrapping works differently in MRI and JRuby. This lead to different docs being generated depending on interpreter.
Here's an example.
MRI:
JRuby:
For code indentation (and actually for any space) in the manual we use Non-breaking Space (NBSP). We do this because Prawn strips any leading whitespaces when it does text layout (presumably to keep the text properly aligned).
When Prawn lays out text it uses a bunch of regular expressions to break the text into words. That regular expression contains `\s` for whitespaces among other things. It turns out that `/\s/` matches NBSP as well. Sometimes.
In MRI `/\s/` matches NBSP in Win-1252 strings but doesn't in UTF-8 strings. JRuby doesn't …

Fix handling of NBSP in Win-1252 encoded strings

---

lib/prawn/errors.rb
lib/prawn/graphics/join_style.rb
spec/stroke_styles_spec.rb

Hey, guys. I wasn't sure how you'd want to handle #988, raise, coalesce to :miter, &c. Right now this raises, but I'm happy to make the change if there's some way you'd rather see this done. 
Cheers!

Raise exception for unrecognized join styles

---

lib/prawn/graphics/color.rb

Picking up stale work from #978 
As noted in that PR, `write_fill_color` and `write_stroke_color` are private methods aren't used anywhere in this project. Removing these because of that and then we can close that PR as well. 
Didn't add any specs, we just use the lower-level `write_color` inside of `set_color`. We do test the public [`stroke_color`](https://github.com/prawnpdf/prawn/blob/master/spec/prawn/graphics_spec.rb#L227) and [`fill_color`](https://github.com/prawnpdf/prawn/blob/master/spec/prawn/graphics_spec.rb#L234) methods so we know that color assignment hasn't been affected.

Remove unnecessary color methods

---

Rakefile
lib/prawn/graphics/patterns.rb
manual/contents.rb
manual/cover.rb
manual/graphics/helper.rb
prawn.gemspec
spec/manual_spec.rb

This is a spec checks if the manual has unexpectedly changed. Addresses #681.
The code for manual generation is changed to make it easier to write a spec for it. Also the manual itself doesn't include the version information when built in the CI environment because it's expected to change and is not essential really that important for the actual manual content.
Blockers:

Manual spec

---

spec/prawn/document_grid_spec.rb
spec/prawn/stamp_spec.rb
spec/prawn/text_spec.rb

There were two trivial whitespace issues and one would-prefer-this-approach issue in the specs. This fixes all three

Fix reported Rubocop warnings

---

lib/prawn/security.rb
lib/prawn/text.rb

We require `pdf/core` in `lib/prawn.rb`, and were requiring
`pdf/core/text` and `pdf/core/byte_string` in `lib/prawn/text.rb` and
`lib/prawn/security.rb` respectively.
Those second requires were causing double-loads and warnings under
certain circumstances because of a bug in Ruby
(https://bugs.ruby-lang.org/issues/10222).
We use objects under the `PDF::Core` namespace freely throught Prawn and
those two requires seem to be both out of character (in the rest of the
codebase it's assumed that `PDF::Core` has already been required), and
overkill (`pdf-core`'s codebase itself generally assumes that all the
objects under its namespace are already required).
I think it's safe to just remove these requires deeper into `pdf-core` -
it makes these double-load problems go away and is more in …

Remove superfluous pdf-core requires

---

CHANGELOG.md
lib/prawn/font/afm.rb
spec/prawn/font_spec.rb

- when an afm font is missing, provide more information to the user
- look for font name in family option in case of missing TTF

resolves #1022 provide more information about missing font

---

GPLv2

rpmlint is picking this error up during a recent update to prawn.
Closes #1088

Fix incorrect address in GPLv2

---

lib/prawn/document.rb
spec/prawn/document_spec.rb

https://github.com/prawnpdf/prawn/issues/958

Add method to delete pages of the document by index

---

lib/prawn/font_metric_cache.rb
spec/prawn/font_spec.rb
spec/prawn/text_spacing_spec.rb
spec/prawn_manual_spec.rb

The value of `character_spacing` should be added to the length of the original string `(string.length - 1)` times instead of `string.length` times, since character_spacing only increases the space between
characters.
Incorrect text width calculation was causing `:center` and `:right` aligned text to be incorrectly positioned when using `character_spacing != 0` (see screenshots).
Note: this was briefly noticed/discussed in https://github.com/prawnpdf/prawn/issues/253.
**Screenshots - current behavior:**
| Alignment | Screenshot |
| --- | --- |
| left | <kbd><img src="https://user-images.githubusercontent.com/32585/57630052-328e1b80-759d-11e9-81fa-3735af8cbbf6.png"/></kbd> |
| center | <kbd><img src="https://user-images.githubusercontent.com/32585/57630090-40dc3780-759d-11e9-9bf4-ab9191c9d56 …

Fix character_spacing effect on text width calculation.

---

lib/prawn/view.rb

Echoes https://github.com/prawnpdf/prawn/issues/802.
I had seen the greeter example in the docs but missed the comment on the document method. I thought it might be helpful to include it in the example as well.

Add documentation about document configuration

---

lib/prawn/graphics/transformation.rb
spec/prawn/graphics_spec.rb
spec/prawn_manual_spec.rb

We have proper number serialization routines provide by PDF::Core but we didn't use them in this case.
Fixes #1178

Fix transformation matrix serialization

---

manual/bounding_box/nesting.rb

There was a misspelling of `outer`, so small PR to correct.

Fix typo in documentation for bounding box nesting

---

prawn.gemspec

Ruby master branch recently bumped the version number to 3.0: https://github.com/ruby/ruby/commit/21c62fb670b1646c5051a46d29081523cd782f11
This is breaking our ruby-head CI.

Update ruby_version requirement to allow ruby 3.0

---

lib/prawn/text/formatted/box.rb
spec/prawn/text/formatted/box_spec.rb

valign for box should have some validation as align does
If there is any reason to have no restriction on valign, please let me know!

Add valign validation

---

lib/prawn/font.rb
lib/prawn/font_metric_cache.rb
spec/prawn/font_metric_cache_spec.rb

This is a proposed fix for #1140 
Since font size is mutable and derived from Prawn::Document, I think it makes the most sense to explicitly include it in the cache key.

Fix font metric caching on Ruby 2.7+

---

CHANGELOG.md
lib/prawn/text/formatted/box.rb
spec/prawn/text/formatted/box_spec.rb

note that this patch adds an optional fourth argument to find_font_for_this_glyph
resolves #1147

Look for glyph in correct font when fallback fonts are enabled

---

lib/prawn/font.rb

I regularly run the [HexaPDF benchmarks](https://hexapdf.gettalong.org/documentation/benchmarks/) to verify that HexaPDF gets only faster. Two benchmarks, "raw_text" and "line_wrapping" also use Prawn to evaluate the relative performance.
When updating to the latest releases I noticed that Prawn seemed to be slower than usual. Therefore I looked at the code to see if I could find some low hanging fruit to optimize. I **did** find some spots that made Prawn faster again although it seems that Prawn generally got a bit slower over time.
**By applying this PR and the other one for `pdf-core` in https://github.com/prawnpdf/pdf-core/pull/45 we will roughly get the performance of Prawn 2.2.0 back**.
Everything was run with Ruby 3.0.0 and using the latest release of Prawn, 2.4.0. Results are …

Reduce memory allocations and enhance performance

---

.github/workflows/ci.yml

Since [Ruby 3.1.0 is out](https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/), we should add it to the CI workflow.
@pointlessone Can you release a new version? `prawn` 2.4.0 fail with Ruby 3.1.0 without adding `matrix` gem to the Gemfile.

Add Ruby 3.1.0 to CI

---

lib/prawn/grid.rb

This addresses #1044 - use a pair of ints rather than a single array of two ints in the documentation, matching the expected behavior.

Fix arguments in documentation comment

---

lib/prawn/document/internals.rb
spec/prawn/graphics_spec.rb

This is a green version of #1097 .  Fixes a lint.
From #1097:
save_graphics_state can take a block form which automatically restores
the graphics state when the block completes. However, the
transformation stack was not being popped in this case.
This fix pops the transformation stack after save_graphics_state is
used in block form.
Thanks to @mogest for the contribution.
@pointlessone This should be ready for merge.

Fix transformation stack not being popped 

---

lib/prawn/security.rb
spec/prawn/document/security_spec.rb

Serialization of encrypted strings is separate from normal serialization. And here there is the problem that \n was escaped instead of \r. So using \r instead of \n yields the correct result.
Fixes #1229

Fix bug when encrypted string contains \r

---

lib/prawn/text/formatted/parser.rb
spec/prawn/text/formatted/parser_spec.rb

This PR exposes the escape and unescape logic for Prawn HTML.
This is a rebased version of the change in #889 .  Thanks to @johnnyshields for the original submission.
@pointlessone this can be merged.

Extract escape and unescape methods in Text::Formatted::Parser module

---

lib/prawn/images.rb

https://github.com/prawnpdf/prawn/blob/30da9f40e5f308f69198879301d65cacca214b69/lib/prawn/images.rb#L58-L62
I ran the code with the above documentation and got the following error.
~~~ruby
require "open-uri"
image open("https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png")
~~~
~~~
No such file or directory @ rb_sysopen - https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
~~~
Perhaps the  [Kernel.#open](https://docs.ruby-lang.org/en/3.1/Kernel.html#method-i-open) has been executed.
So I modified it as follows and it performed as expected.
~~~ruby
image URI.open("https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png")
~~~
If there is another way to solve this problem, I would appreciate it if you …

Fix images.rb document

---

lib/prawn/text.rb
spec/prawn/text_spec.rb

In case of no indent_paragraphs when formatted_text is called it
passes the text to render to Text.fill_formatted_text_box. Then the text
is rendered using the Box class and the Box class in combination with
the Wrap module takes care of spacing between lines. Spacing is present
regardless of final_gap value.
In case of indent_paragraphs set the situation is different.
formatted_text itself prints the first line separately and then the rest
of the text. As such, it has the responsibility to add spacing between
the first line and the rest on its own. When final_gap is set, as it is
by default, it works just fine. When final_gap is not set though, there
was no space between the first line and the second line of the text.
Since formatted_text calls draw_indented_formatted_line to render the …

Fix indent_paragrahs/no final_gap line spacing bug

---

lib/prawn/images.rb

There is a typo in the images function docs that shows a nonexistent option `topm`.

Fix typo in images function docs

---

README.md

I've never actually used this library myself but I've seen it consistently come up as the current HTML to PDF option that people prefer, and I believe it has no dependencies other than Chrome.

Link to Ferrum rather than outdated HTML to PDF generators

---

lib/prawn.rb
prawn.gemspec
spec/prawn/document/security_spec.rb

- Following on from https://github.com/prawnpdf/prawn-dev/pull/2  like I said I would.
- Interestingly RuboCop didn’t complain about what I expected it to complain about (the non-parenthesized `puts`, for one) so I don’t know what I’m doing wrong?

Bump `prawn-dev` and fix RuboCop offenses

---

lib/prawn/text/formatted/box.rb
spec/prawn/text/formatted/box_spec.rb

Problem:
Using an unsupported symbol for the value of 'valign' on a text box throws a misleading error message. 
Solution:
This adjusts the error message to match the actual values supported by the code.

Revise confusing 'valign' error message for text boxes
